### ISSUE TITLE
TS01 - Configuração do ambiente 

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#10]
## Descrição
Eu, **como** desenvolvedor, **desejo** gostaria de configurar o ambiente de desenvolvimento  **para que eu possa** iniciar o projeto.

## Critérios de aceitação
- [x] Ambiente deve ser criado usando docker
- [x] Makefile deve estar configurado com principais comando 
- [x] Comandos devem ser documentados com instruções para desenvolvedores

**Comment by rafaelmakaha** [comment]
Issue fechada pelo pr #11
