### ISSUE TITLE
US05 - Telas de recuperação de senha

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#18]
## Descrição
Criação das telas personalizadas de recuperação de senha de acordo com o estilo do protótipo

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Telas estão personalizadas em português
- [x] Grupo aprova o design das telas

**Comment by andrelucax** [comment]
nao existe as telas de esqueci senha no [prototipo](https://www.figma.com/proto/tN6ggOP6Tnvm2iMgVPt2R1/Untitled?node-id=74%3A5&scaling=contain)

**Comment by gustavolima00** [comment]
Só o estilo deve seguir o protótipo, como cor, fonte, tamanho de fonte, a organização da tela pode continuar a mesma :)
