### ISSUE TITLE
Bug - Erro ao registrar sem nome 

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#22]
## Descrição
Ao realizar o registro sem mandar o campo de nome o servidor retorna um erro 500

## Passos Para Reproduzir o _Bug_
1 - Rodar o servidor
2 - Enviar requisição pra /registration/ com apenas os campos de email e password

![image](https://user-images.githubusercontent.com/32046134/66776379-9a25fb00-ee9c-11e9-9b78-c5e3fa003fb1.png)
![image](https://user-images.githubusercontent.com/32046134/66776397-a5792680-ee9c-11e9-8282-2461458dae2d.png)

## Comportamento Esperado
* Seridor fazer registro sem o nome

**Comment by andrelucax** [comment]
Resolvido no [PR](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/23)
