### ISSUE TITLE
US01 - Confirmação de email ao criar conta

### ISSUE THREAD

**Issue by leomedeiros1** [2019-2-arquitetura-desenho/monitoria-api#27]
## Descrição
Deve ser adicionada a verificação do email ao cadastrar uma nova conta. Esta ação deve ocorrer no momento do cadastra, via uma mensagem de email, e a nova conta deve permanecer bloqueada até que o email seja verificado.

## Critérios de aceitação
- [ ] Ao criar uma conta, deverá ser enviada uma mensagem de email com um link para verificação da senha.
- [ ] Nova conta deve ficar bloqueada até que a verificação seja concluída.

**Comment by PauloVitorRocha** [comment]
Foi decidido pela equipe que não será feita mais a confirmação de email.
