### ISSUE TITLE
TS07 - Cadastro em turma

### ISSUE THREAD

**Issue by leomedeiros1** [2019-2-arquitetura-desenho/monitoria-api#31]
## Descrição
Deve ser criada uma estrutura referente a uma disciplina/turma para que os usuários (alunos) possam cadastrar-se na mesma. 

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Deve ser possível que usuários possam inscrever-se para está turma.
- [x] A estrutura deve ser responsável por armazenar os alunos que se inscreveram nela organizados por sua nota calculada para esta disciplina.
- [x] A estrutura deve ter suporte para que em um momento futuro possa ser consultada a lista de alunos.

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [ ] Funcionalidade deve ser testada.

**Comment by andrelucax** [comment]
resolvida em [Disciplinas #43](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/43)
