### ISSUE TITLE
US21 - Gerenciar período de inscrição

### ISSUE THREAD

**Issue by leomedeiros1** [2019-2-arquitetura-desenho/monitoria-api#32]
## Descrição
Deve ser criada uma estrutura para controle de um período de matricula, incluindo tempo de duração e numero de vagas em disciplinas.

## Issues relacionadas
*Issues que devem ser completadas antes desta ser iniciada*
[Cadastro em turma](#31 )
## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] A estrutura deve fazer controle do tempo, tendo data de inicio e de termino.
- [x] A estrutura deve ser capaz de manter a relação de alunos inscritos em cada turma durante o período.
- [ ] A estrutura deve ser capaz de gerar um relatório final, contendo a lista de aprovados para cada turma.

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [ ] Funcionalidade deve ser testada.

**Comment by andrelucax** [comment]
resolvida em [Disciplinas #43](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/43)
