### ISSUE TITLE
TS06 - Anexar dados do pdf ao perfil de aluno

### ISSUE THREAD

**Issue by leomedeiros1** [2019-2-arquitetura-desenho/monitoria-api#33]
## Descrição
As informações extraídas no modulo pdf extractor devem ser adicionadas ao perfil de aluno, incluindo o link para o arquivo original no CDN.

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Deve ser configurado o CDN para armazenar os pdfs inseridos pelos usuários.
- [x] Devem ser adicionadas as informações extraídas ao perfil de aluno.

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [x] Funcionalidade deve ser testada

**Comment by PauloVitorRocha** [comment]
Show!
