### ISSUE TITLE
Bug - Assincronidade de serviços em Containeres

### ISSUE THREAD

**Issue by rafaelmakaha** [2019-2-arquitetura-desenho/monitoria-api#34]
## Descrição
Ao se inicializar os containeres pela primeira vez, o container que comporta do Django está programado apenas para esperar a criação do container do Postgres.
Com isso, o serviço do django tenta executar uma conexão com o banco de dados antes mesmo deste estar disponível, causando o encerramento do serviço no django.

## Passos Para Reproduzir o _Bug_
1 - Remover qualquer container já executado anteriormente
2 - Executar o comando "make server"
3 - Visualizar que o container do django retorna falha de conexão com o banco de dados

![Screenshot from 2019-11-11 10-50-01](https://user-images.githubusercontent.com/20361663/68592255-5a3d3e00-0471-11ea-9d10-2bb21a311ce2.png)

## Comportamento Esperado
* O serviço do Django deve esperar a disponibilidade do postgres para realizar conexões

|  Browser	| OS 	|
|------------------	|------------	|
|           Chromium           |       Ubuntu 18       |

**Comment by PauloVitorRocha** [comment]
@rafaelmakaha não consegui reproduzir o bug. Segui os seguintes passos:
```
sudo docker system prune
make server
```
![Screenshot from 2019-11-11 21-43-02](https://user-images.githubusercontent.com/37215459/68632173-5db1e300-04cc-11ea-95a1-0b8dcfaed521.png)

teria algum passo extra para reproduzi-lo, ou estou fazendo algo errado?

**Comment by rafaelmakaha** [comment]
@PauloVitorRocha 
Você esqueceu de remover os containeres.
Seguem os comandos:
docker ps 
docker rm <id_container> # remova o container do monitoria-api e o postgres
make server

O problema me foi relatado na segunda-feira pelo @leomedeiros1

**Comment by leomedeiros1** [comment]
Resolvido em [BugFix - Sincronização de serviços em Containeres](https://github.com/2019-2-arquitetura-desenho/monitoria-api/issues/34).
