### ISSUE TITLE
TS05 - Utilizar o crawler para retornar as matérias

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#37]
## Descrição
Integração entre api e crawler no intuito de filtrar matérias do estudante

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Matérias devem conter informações completas e não só o código, como existe agora
- [x] As matérias devem ser filtradas para as que estão contidas no perfil do estudante

**Comment by leomedeiros1** [comment]
Resolvido em [Connecting student subject code with crawler subjects #38 ](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/38)
