### ISSUE TITLE
US01 - Criação de perfil

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#4]
## Descrição
Criação de perfil associado à um usuário cadastrado, referente a [US01](https://2019-2-arquitetura-desenho.github.io/wiki/dinamica_seminario_II/backlog_do_produto/#us01)

### Issues relacionadas
*Issues que devem ser fechadas antes dessa ser iniciada*
[Cadastro](https://github.com/2019-2-arquitetura-desenho/monitoria-api/issues/3)

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] O perfil deve ter um usuário cadastrado associado 
- [x] Devem ser criados perfis de Aluno e Professor
- [x] Perfil deve conter informações básicas do usuário contidas no [Diagrama de classe](https://2019-2-arquitetura-desenho.github.io/wiki/dinamica_seminario_III/diagrama_classes/#diagrama-geral-backend)

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [x] Funcionalidade deve ser testada

**Comment by WelisonR** [comment]
Fechada pelo PR #14.
