### ISSUE TITLE
Bug - Criar usuário com url de pdf inválido

### ISSUE THREAD

**Issue by PauloVitorRocha** [2019-2-arquitetura-desenho/monitoria-api#40]
## Descrição

O usuário estava sendo capaz de criar uma conta enviando um pdf inválido.
## Passos Para Reproduzir o _Bug_
1 - Faça o registro de um usuário com um link de pdf válido na url localhost:8000/registration.
2 - Logo após isso, crie um usuário  com um link de pdf inválido.

## Comportamento Esperado
* O usuário deveria receber a mensagem de erro "pdf inválido".

**Comment by leomedeiros1** [comment]
Corrigida pelo PR: [Bugfix/pdf reader](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/41)
