### ISSUE TITLE
US03 - Alterar informações do perfil

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#7]
## Descrição
Eu, **como** usuário, **desejo** alterar minhas informações de cadastro **para que eu possa** atualizá-las
Usuário deve conseguir alterar informações contidas em seu perfil. Relacionada a [US03](https://2019-2-arquitetura-desenho.github.io/wiki/dinamica_seminario_II/backlog_do_produto/#us03)

### Issues relacionadas
*Issues que devem ser fechadas antes dessa ser iniciada*
[Criação de perfil](#4 )

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Usuário consegue alterar informações em seu perfil
- [x] Alterações são persistidas no banco de dados

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [x] Funcionalidade testada deve ser testada

**Comment by WelisonR** [comment]
Fechada pelo PR #14.
