### ISSUE TITLE
US 04 - Deletar conta

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#8]
## Descrição
Usuário deve conseguir deletar sua conta removendo todos os dados associados. Referente a [US04](https://2019-2-arquitetura-desenho.github.io/wiki/dinamica_seminario_II/backlog_do_produto/#us04)

### Issues relacionadas
*Issues que devem ser fechadas antes dessa ser iniciada*
[Criação de perfil](#4)

## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [ ] Dados devem ser preservados no banco de dados (exclusão lógica).

## Critérios adicionais
*Critérios que devem ser realizados porém que podem ser deixados como dívida técnica gerando novas issues*
- [ ] Funcionalidade deve ser testada
- [ ] Deve ser aplicado sistema de segurança prevendo erros de exclusão de perfil acidentais

**Comment by leomedeiros1** [comment]
Funcionalidade removida.
