### ISSUE TITLE
US05 - Recuperação de senha

### ISSUE THREAD

**Issue by gustavolima00** [2019-2-arquitetura-desenho/monitoria-api#9]
## Descrição
Eu, **como** usuário, **desejo** recuperar minha senha **para que eu possa** recuperar o acesso à minha conta
Usuário deve ser capaz de recuperar sua senha caso tenha esquecido

## Issues relacionadas
*Issues que devem ser fechadas antes desse issue ser iniciada*
[Cadastro](#3)
## Critérios de aceitação
*Critérios essenciais para a funcionalidade que não podem ser deixados como dívida técnica*
- [x] Usuário deve recuperar senha utilizando seu e-mail
- [x] Nova senha deve persistir no banco de dados
- [x] Antiga senha não deve funcionar mais

**Comment by andrelucax** [comment]
Issue resolvida no [PR15](https://github.com/2019-2-arquitetura-desenho/monitoria-api/pull/15)
